title: ToolCraft Documentation
library_name: toolcraft
repo_url: https://github.com/SpikingNeurons/toolcraft
version: main

# Navigation and theme
navbar_start:
  - title: "Home"
    url: "index"

# Additional configuration
code_sample_max_depth: 3
edit_page: true
github_url: https://github.com/SpikingNeurons/toolcraft

# Search configuration
search:
  enable: true

# Theme customization
theme:
  name: "huggingface"
  sidebar_width: "300px"
