name: CLA Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

# Explicitly grant permissions
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The branch where the signatures will be stored
          BRANCH: 'cla-signatures'
          # Path to the CLA document
          PATH_TO_DOCUMENT: 'https://github.com/SpikingNeurons/toolcraft/blob/main/CLA.md'
          # Path to the signatures file
          PATH_TO_SIGNATURES: 'cla-signatures.json'
          # Custom CLA message
          CUSTOM_NOTSIGNED_PRCOMMENT: 'Thank you for your submission! We require contributors to sign our Contributor License Agreement (CLA), and we don''t have a record of your signature. Please review and sign our [CLA]($pathToCLA). Once you sign the CLA, we''ll be able to review your contribution.<br/><br/>**To sign the CLA, please comment on this PR with:**<br/>`I have read the CLA Document and I hereby sign the CLA`'
          CUSTOM_PR_SIGN_COMMENT: 'I have read the CLA Document and I hereby sign the CLA'
          CUSTOM_ALLSIGNED_PRCOMMENT: 'All contributors have signed the CLA ✅'
          # Don't use a blocklist for now
          # CUSTOM_NOTSIGNED_PRCOMMENT: 'Thank you for your submission, we require contributors to sign our [Contributor License Agreement]($pathToCLA). This automated message is to let you know that we don''t have a record of your CLA signature. Please review and sign our CLA.'
